### ISSUE TITLE
Switch the name field to be separate first+last name fields

### ISSUE THREAD

**Issue by evan10s** [HackGT/ground-truth#3]
A necessary change that will make name handling more robust in our various apps by

1) Ensuring we get complete information (e.g., validation to prevent entering John D. for your name)
2) More personal mail merge greetings (e.g., Hi John instead of Hi John Doe)
3) Not having to refer to people by their full name all the time on our user interfaces
4) Being able to sort by last name without having to using string splitting and make guesses

**Comment by joel99** [comment]
What about people with more than two names? Should write in text the
standard preferred approach (probably all but last name in first name field)

**Comment by evan10s** [comment]
I think an issue with first + last name is some people go by a preferred name.  I've seen elsewhere doing legal first name, legal last name, preferred first name to solve that.
________________________________

**Comment by petschekr** [comment]
Fixed by #7
